
language: cpp
os: linux
dist: trusty
group: travis_latest
sudo: false

matrix:
  include:
    - env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      addons: { apt: { packages: ["clang-4.0"], sources: ["llvm-toolchain-trusty-4.0", "ubuntu-toolchain-r-test"] } }

    - env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    # compiler
      - ninja-build
    # doc tools
      - doxygen
      - graphviz
      - mscgen

install:
  - eval "${MATRIX_EVAL}"
  - ${CXX} --version
  # install CMake 3.10
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - echo "020740ee9132f55aa529782ee9f578ec *cmake-3.10.0-Linux-x86_64.tar.gz" > cmake_md5.txt
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.10.0-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.10.0-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - |
    if [[ "${CXX}" == "g++-7" ]]; then
        cd ${TRAVIS_BUILD_DIR}
        mkdir build-coverage
        cd build-coverage
        cmake -DCMAKE_BUILD_TYPE=Debug -DGB_GENERATE_COVERAGE_INFO=ON -DGCOV_COMMAND=gcov-7 ..
        cmake --build .
    fi
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build
  - ctest -C Release
  - |
    if [[ "${CXX}" == "g++-7" ]]; then
        cd ../build-coverage
        ctest -C Debug
    fi
  - cd ${TRAVIS_BUILD_DIR}

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build-coverage
  - |
    if [[ "${CXX}" == "g++-7" ]]; then
        cmake --build . --target gbMath_TestCoverage
        bash <(curl -s https://codecov.io/bash)
    fi
